// Generated by data/build_data.py from the files in data/ — edit those, not this.
const DOMAIN_DATA = {
 "AI & Data Science": {
  "about": "Transforms raw data into intelligence that informs decisions, powers products, and automates judgment. The function responsible for extracting signal from noise — and increasingly, for embedding that intelligence directly into business systems.",
  "indices": [
   [
    "Insight Actionability",
    "degree to which findings drive decisions"
   ],
   [
    "Model Performance",
    "accuracy, precision & reliability of outputs"
   ],
   [
    "Data Trustworthiness",
    "quality, lineage & integrity of data assets"
   ],
   [
    "Intelligence Adoption",
    "uptake of AI/analytics outputs across the business"
   ]
  ],
  "capabilities": [
   "Data Analysis & Visualisation",
   "Statistical Modelling",
   "Machine Learning",
   "Deep Learning & AI Research",
   "NLP & Generative AI",
   "Data Strategy & Governance",
   "MLOps & Model Deployment",
   "Business Intelligence",
   "Experimentation & A/B Testing"
  ],
  "deliverables": [
   {
    "id": "AI-01",
    "service": "Predictive Model Development",
    "name": "Trained Predictive Model",
    "desc": "Building an ML model that predicts a defined business outcome from historical data, validated before handover."
   },
   {
    "id": "AI-02",
    "service": "Exploratory Data Analysis & Insight Generation",
    "name": "Data Analysis Report",
    "desc": "Analysing a dataset to surface patterns, trends, and actionable findings for a specific business question."
   },
   {
    "id": "AI-03",
    "service": "Business Intelligence Dashboard Development",
    "name": "BI Dashboard",
    "desc": "Designing and building a recurring BI dashboard surfacing defined business metrics for ongoing monitoring."
   },
   {
    "id": "AI-06",
    "service": "NLP Application Development",
    "name": "NLP Application / Service",
    "desc": "Building an application that processes or generates natural language for a defined business use case."
   },
   {
    "id": "AI-07",
    "service": "Generative AI Agent / Assistant Development",
    "name": "Deployed AI Agent",
    "desc": "Building an LLM-powered conversational agent or assistant that performs a defined set of tasks for users."
   },
   {
    "id": "AI-08",
    "service": "Model Deployment & MLOps Pipeline Build",
    "name": "MLOps Pipeline",
    "desc": "Building the infrastructure and pipeline that takes a trained model into production — serving, versioning, monitoring."
   },
   {
    "id": "AI-09",
    "service": "Model Performance Monitoring & Drift Detection",
    "name": "Model Monitoring Dashboard & Alerts",
    "desc": "Implementing monitoring that tracks a deployed model's accuracy and detects data or concept drift over time."
   },
   {
    "id": "AI-10",
    "service": "Data Quality Audit & Governance Framework",
    "name": "Data Governance Framework & Audit Report",
    "desc": "Assessing data quality, lineage, and governance, and designing a framework to maintain data trustworthiness."
   },
   {
    "id": "AI-12",
    "service": "Recommendation System Development",
    "name": "Recommendation Engine",
    "desc": "Building a system that generates personalised recommendations based on behavioural or content data."
   },
   {
    "id": "AI-13",
    "service": "Forecasting Model Development",
    "name": "Forecasting Model & Output Report",
    "desc": "Building a time-series forecasting model to predict future values of a business metric."
   },
   {
    "id": "AI-14",
    "service": "Computer Vision Application Development",
    "name": "Computer Vision Application / Service",
    "desc": "Building an application that processes and interprets visual data for a defined business use case."
   },
   {
    "id": "AI-18",
    "service": "Data Visualisation & Insight Communication",
    "name": "Data Visualisation Deliverable",
    "desc": "Designing clear visualisations that communicate data-driven findings to a specific audience."
   },
   {
    "id": "AI-19",
    "service": "Synthetic Data Generation Pipeline",
    "name": "Synthetic Data Pipeline",
    "desc": "Building a pipeline that generates synthetic data matching source statistical properties, for augmentation or privacy."
   }
  ]
 },
 "Business, Sales & Growth": {
  "about": "Generates and expands the revenue a business needs to survive and scale. The function that connects the value a business creates to the markets willing to pay for it — through selling, partnering, and finding new frontiers for growth.",
  "indices": [
   [
    "Revenue Growth Rate",
    "pace of top-line expansion"
   ],
   [
    "Pipeline Quality",
    "conversion strength and deal progression"
   ],
   [
    "Market Expansion Depth",
    "penetration into new segments or geographies"
   ],
   [
    "Partnership Value Realised",
    "commercial outcomes from alliances and channels"
   ]
  ],
  "capabilities": [
   "Sales Execution",
   "Business Development",
   "Account Management",
   "Partnerships & Alliances",
   "Revenue Operations",
   "Go-to-Market Strategy",
   "Market Expansion",
   "Competitive Intelligence",
   "Proposal & Deal Structuring"
  ],
  "deliverables": [
   {
    "id": "BG-05",
    "service": "Go-to-Market Strategy",
    "name": "GTM Strategy",
    "desc": "Defining the commercial route to market — segments, channels, motion, and revenue model — for a business or offer."
   },
   {
    "id": "BG-08",
    "service": "Partnership Development & Alliance Strategy",
    "name": "Partnership Strategy & Pipeline",
    "desc": "Identifying and designing commercial partnerships and alliances that open new revenue or distribution."
   },
   {
    "id": "BG-09",
    "service": "Channel & Reseller Program Design",
    "name": "Channel Program",
    "desc": "Designing a channel or reseller programme — partner tiers, incentives, enablement, and economics."
   },
   {
    "id": "BG-10",
    "service": "Market Entry & Expansion Strategy",
    "name": "Market Entry Plan",
    "desc": "Assessing and planning entry into a new market segment or geography, with a sequenced expansion plan."
   },
   {
    "id": "BG-11",
    "service": "Competitive Intelligence Analysis",
    "name": "Competitive Intelligence Report",
    "desc": "Researching competitors' commercial positioning and tactics to sharpen sales and win strategy."
   },
   {
    "id": "BG-12",
    "service": "Account Growth & Expansion Strategy",
    "name": "Account Growth Plan",
    "desc": "Designing the plan to grow revenue within existing accounts — upsell, cross-sell, and expansion paths."
   },
   {
    "id": "BG-16",
    "service": "Lead Generation Strategy",
    "name": "Lead Generation Strategy",
    "desc": "Designing the strategy and channels through which qualified commercial leads are generated."
   },
   {
    "id": "BG-17",
    "service": "Strategic Business Development Plan",
    "name": "Business Development Plan",
    "desc": "Defining the plan for new commercial growth — markets, partners, and opportunities to pursue."
   },
   {
    "id": "BG-19",
    "service": "Win/Loss Analysis Program",
    "name": "Win/Loss Report",
    "desc": "Systematically analysing why deals are won or lost to improve commercial strategy and product fit."
   },
   {
    "id": "BG-20",
    "service": "Pricing & Monetisation Strategy",
    "name": "Pricing Strategy",
    "desc": "Defining the commercial pricing and monetisation approach for an offer, grounded in value and market."
   },
   {
    "id": "BG-21",
    "service": "Account & Prospect Research",
    "name": "Prospect Research Dossier",
    "desc": "A structured, source-backed dossier on a target account covering firmographic discovery, deeper intelligence enrichment (initiatives, signals, fit), a decision-maker / founder contact path, and a completeness assessment flagging what is known, what is missing, and where to look next."
   }
  ]
 },
 "Design": {
  "about": "Gives form, feeling, and clarity to a business's products and communications. The function that shapes how people experience and understand what a business makes — bridging aesthetic judgment with functional intent.",
  "indices": [
   [
    "Usability & Task Success",
    "ease with which users achieve intended outcomes"
   ],
   [
    "Visual & Brand Consistency",
    "coherence of design language across touchpoints"
   ],
   [
    "Experience Satisfaction",
    "perceived quality and delight of the interaction"
   ],
   [
    "Design-to-Build Fidelity",
    "accuracy of realised output vs designed intent"
   ]
  ],
  "capabilities": [
   "UX Research & Testing",
   "Interaction Design",
   "Visual & UI Design",
   "Brand & Identity Design",
   "Service Design",
   "Design Systems",
   "Prototyping",
   "Motion & Animation",
   "Design Strategy"
  ],
  "deliverables": [
   {
    "id": "DS-01",
    "service": "Brand & Visual Identity Design",
    "name": "Visual Identity System",
    "desc": "Designing a brand's complete visual identity system — logo, colour, typography, and usage rules."
   },
   {
    "id": "DS-02",
    "service": "Digital Product UI Design",
    "name": "High-Fidelity UI Design",
    "desc": "Designing the high-fidelity visual interface of a digital product — screens, states, and visual language."
   },
   {
    "id": "DS-03",
    "service": "Interaction Design",
    "name": "Interaction Design Specification",
    "desc": "Designing how a user moves through and interacts with an interface — flows, states, and micro-interactions."
   },
   {
    "id": "DS-04",
    "service": "Design System Build",
    "name": "Design System",
    "desc": "Architecting a reusable component library, tokens, and documentation as the craft foundation of a product's UI."
   },
   {
    "id": "DS-05",
    "service": "UX Research & Usability Testing",
    "name": "UX Research Findings",
    "desc": "Conducting design-focused user research and usability testing to inform and validate design decisions."
   },
   {
    "id": "DS-06",
    "service": "Service Design & Blueprinting",
    "name": "Service Blueprint",
    "desc": "Designing the end-to-end service experience across frontstage and backstage touchpoints."
   },
   {
    "id": "DS-07",
    "service": "Motion & Animation Design",
    "name": "Motion Design Assets",
    "desc": "Designing motion, transitions, and animated assets that bring an interface or brand to life."
   },
   {
    "id": "DS-08",
    "service": "Interactive Prototype Design",
    "name": "Interactive Prototype",
    "desc": "Building a design-led interactive prototype to communicate and validate an experience."
   },
   {
    "id": "DS-09",
    "service": "Design Strategy & Vision",
    "name": "Design Strategy Document",
    "desc": "Defining the long-range design direction and principles that guide a product or brand's experience."
   },
   {
    "id": "DS-10",
    "service": "Design Audit & Heuristic Evaluation",
    "name": "Design Audit Report",
    "desc": "Expert review of an existing experience against usability and design-quality heuristics, with prioritised fixes."
   },
   {
    "id": "DS-11",
    "service": "Iconography & Illustration Design",
    "name": "Icon / Illustration Set",
    "desc": "Designing a cohesive set of icons or illustrations aligned to a brand or product's visual language."
   },
   {
    "id": "DS-12",
    "service": "Accessibility Design Review",
    "name": "Accessibility Audit Report",
    "desc": "Auditing a design against accessibility standards (WCAG) and recommending inclusive design improvements."
   },
   {
    "id": "DS-13",
    "service": "Wireframing & Lo-Fi Layout Design",
    "name": "Wireframes",
    "desc": "Producing low-fidelity structural layouts that define screen content and hierarchy before visual design."
   },
   {
    "id": "DS-14",
    "service": "Presentation & Pitch Deck Design",
    "name": "Designed Presentation Deck",
    "desc": "Designing a polished, on-brand presentation or pitch deck that communicates a narrative visually."
   },
   {
    "id": "DS-15",
    "service": "Marketing & Email Template Design",
    "name": "Template Design Set",
    "desc": "Designing reusable on-brand templates for email, social, or marketing assets."
   },
   {
    "id": "DS-17",
    "service": "Packaging & Print Design",
    "name": "Print / Packaging Artwork",
    "desc": "Designing physical packaging or print collateral aligned to a brand's identity."
   },
   {
    "id": "DS-18",
    "service": "Information Architecture & Wayfinding Design",
    "name": "Information Architecture Design",
    "desc": "Structuring content and navigation from a design-craft perspective to optimise findability and flow."
   },
   {
    "id": "DS-19",
    "service": "Design Concept Exploration",
    "name": "Design Concept Set",
    "desc": "Exploring multiple divergent design directions for a product or brand before converging on one."
   },
   {
    "id": "DS-20",
    "service": "Logo & Wordmark Design",
    "name": "Logo Suite",
    "desc": "Designing a distinctive logo or wordmark as the central mark of a brand identity."
   }
  ]
 },
 "Marketing & Communications": {
  "about": "Shapes how the business is perceived, discovered, and trusted. The function that builds and sustains the relationship between a brand and its audience — across every channel, message, and moment of contact.",
  "indices": [
   [
    "Brand Salience",
    "top-of-mind presence in target audience"
   ],
   [
    "Audience Trust & Credibility",
    "perceived reliability and authority"
   ],
   [
    "Narrative Clarity",
    "coherence and consistency of messaging"
   ],
   [
    "Demand Generation Efficiency",
    "quality of pipeline created per rupee spent"
   ],
   [
    "Audience Growth & Reach",
    "expansion of addressable and engaged audience"
   ]
  ],
  "capabilities": [
   "Brand Strategy",
   "Content Creation & Strategy",
   "Performance Marketing",
   "SEO & Organic Growth",
   "Narrative & Messaging Design",
   "Community Building",
   "PR & Media Relations",
   "Campaign Planning & Execution",
   "Partnerships & Collaborations",
   "Marketing Analytics"
  ],
  "deliverables": [
   {
    "id": "MK-01",
    "service": "Brand Strategy Development",
    "name": "Brand Strategy Document",
    "desc": "A structured written artefact covering brand positioning, target audience, personality, tone of voice, key messages, and competitive differentiation."
   },
   {
    "id": "MK-02",
    "service": "Marketing Strategy & Annual Planning",
    "name": "Marketing Strategy & Plan",
    "desc": "A comprehensive document defining marketing objectives, audience segments, channel strategy, budget allocation, and a phased activity calendar for the year."
   },
   {
    "id": "MK-03",
    "service": "Go-to-Market Communications Planning",
    "name": "GTM Communications Plan",
    "desc": "A launch-specific communication blueprint covering core narrative, audience-by-channel message mapping, sequencing logic, and an activation timeline."
   },
   {
    "id": "MK-04",
    "service": "Messaging Architecture & Narrative Design",
    "name": "Messaging Architecture Document",
    "desc": "A layered document defining the master brand narrative, key message pillars, proof points per pillar, and audience/channel-specific message variants."
   },
   {
    "id": "MK-05",
    "service": "Competitive Positioning Analysis",
    "name": "Competitive Positioning Report",
    "desc": "A structured analysis of competitor messaging, visual identity, channel mix, and positioning angles, synthesised into actionable positioning recommendations."
   },
   {
    "id": "MK-06",
    "service": "Content Strategy Design",
    "name": "Content Strategy Document",
    "desc": "A written framework covering content pillars, audience personas, channel-content mapping, editorial calendar logic, tone of voice guidelines, and success metrics."
   },
   {
    "id": "MK-07",
    "service": "Campaign Content Creation",
    "name": "Campaign Content Pack",
    "desc": "A complete set of ready-to-publish creative assets for a defined campaign, including copy, imagery briefs or finished assets, and channel-adapted variants."
   },
   {
    "id": "MK-08",
    "service": "Influencer & Creator Script Writing",
    "name": "Influencer Script Set",
    "desc": "A set of platform-native, brand-aligned scripts (with hooks, narrative body, and CTAs) written for specific creator briefs, ready for recording or adaptation."
   },
   {
    "id": "MK-09",
    "service": "SEO Content Production",
    "name": "SEO Content Assets",
    "desc": "A set of keyword-targeted, editorially sound content pieces optimised for search — including meta data, heading structure, and internal linking guidance."
   },
   {
    "id": "MK-10",
    "service": "Copywriting & Ad Creative Development",
    "name": "Ad Copy & Creative Pack",
    "desc": "A set of tested copy variants for ads, emails, or landing pages — structured by funnel stage and format, with headline, body, and CTA for each."
   },
   {
    "id": "MK-11",
    "service": "Integrated Campaign Planning & Execution",
    "name": "Integrated Campaign Plan & Report",
    "desc": "An end-to-end campaign document covering objectives, audience, creative strategy, channel plan, budget, timeline, and a post-campaign performance summary."
   },
   {
    "id": "MK-12",
    "service": "Performance Marketing Campaign Management",
    "name": "Performance Campaign Report",
    "desc": "A structured report covering campaign setup, spend allocation, audience targeting, creative performance, KPI results, and optimisation recommendations."
   },
   {
    "id": "MK-13",
    "service": "Email Marketing Campaign Design",
    "name": "Email Campaign Pack",
    "desc": "A complete email campaign deliverable including segmentation logic, subject lines, email copy, design brief, send schedule, and performance benchmarks."
   },
   {
    "id": "MK-14",
    "service": "Influencer Marketing Campaign Management",
    "name": "Influencer Campaign Report",
    "desc": "A campaign summary covering influencer selection rationale, brief documentation, content delivery tracking, performance metrics, and learnings."
   },
   {
    "id": "MK-15",
    "service": "Audience Research & Persona Development",
    "name": "Audience Research Report & Personas",
    "desc": "A research-backed set of audience personas with demographic, psychographic, behavioural, and channel-preference data — used to sharpen targeting and messaging."
   },
   {
    "id": "MK-16",
    "service": "Brand Health & Perception Research",
    "name": "Brand Health Report",
    "desc": "A structured analysis of brand awareness, net sentiment, key associations, and perception gaps relative to competitive benchmarks, with actionable recommendations."
   },
   {
    "id": "MK-17",
    "service": "Campaign Effectiveness Research",
    "name": "Campaign Effectiveness Report",
    "desc": "A post-campaign research report measuring brand lift, message recall, audience sentiment shift, and behavioural impact attributable to the campaign."
   },
   {
    "id": "MK-18",
    "service": "Community Building & Engagement Strategy",
    "name": "Community Strategy Document",
    "desc": "A blueprint covering community purpose, platform selection, engagement frameworks, content rituals, moderation guidelines, and growth mechanisms."
   },
   {
    "id": "MK-19",
    "service": "PR & Media Relations Campaign",
    "name": "PR Campaign & Coverage Report",
    "desc": "A deliverable including press release drafts, media list, outreach strategy, spokesperson talking points, and a post-campaign earned media summary."
   },
   {
    "id": "MK-20",
    "service": "Partnerships & Co-Marketing Strategy",
    "name": "Partnerships & Co-Marketing Plan",
    "desc": "A structured plan identifying priority partner profiles, value exchange logic, campaign collaboration formats, and a negotiation and activation roadmap."
   },
   {
    "id": "MK-21",
    "service": "Marketing Analytics & Reporting Framework",
    "name": "Marketing Analytics Framework",
    "desc": "A documented system defining the marketing KPI hierarchy, attribution model, dashboard structure, data source mapping, and reporting cadence."
   },
   {
    "id": "MK-22",
    "service": "SEO Audit & Organic Growth Strategy",
    "name": "SEO Audit & Growth Roadmap",
    "desc": "A structured audit covering technical SEO, on-page quality, content gaps, backlink profile, and a prioritised action plan for organic growth improvement."
   }
  ]
 },
 "Product": {
  "about": "Defines what gets built and why. The function that sits at the intersection of user need, business viability, and technical feasibility — translating strategy into a coherent product that evolves with the market.",
  "indices": [
   [
    "Product-Market Fit",
    "alignment between product and real user need"
   ],
   [
    "Feature Value Ratio",
    "utility delivered per unit of build effort"
   ],
   [
    "Retention & Engagement Depth",
    "stickiness and habitual use over time"
   ],
   [
    "Roadmap Coherence",
    "strategic alignment of prioritisation decisions"
   ]
  ],
  "capabilities": [
   "User Research & Discovery",
   "Product Strategy",
   "Roadmap Planning",
   "Prioritisation & Scoping",
   "Stakeholder Alignment",
   "Metrics & Analytics",
   "Go-to-Market Planning",
   "Growth & Experimentation",
   "Product Operations"
  ],
  "deliverables": [
   {
    "id": "PR-01",
    "service": "Product Strategy Development",
    "name": "Product Strategy Document",
    "desc": "Defining the long-range direction of a product or portfolio — positioning, strategic bets, alignment to business objectives."
   },
   {
    "id": "PR-02",
    "service": "Product Roadmap Design",
    "name": "Product Roadmap",
    "desc": "Creating a time-oriented, outcome-driven plan of what will be built, in what order, and why."
   },
   {
    "id": "PR-03",
    "service": "Product Vision & Narrative Design",
    "name": "Product Vision Statement & Narrative",
    "desc": "Articulating a compelling, future-oriented story of what a product is becoming, to align teams and inspire confidence."
   },
   {
    "id": "PR-04",
    "service": "Competitive Landscape Analysis",
    "name": "Competitive Intelligence Report",
    "desc": "Mapping the competitive environment — players, gaps, differentiators, threats — to inform product decisions."
   },
   {
    "id": "PR-06",
    "service": "User Research Programme Design & Execution",
    "name": "User Research Report",
    "desc": "Planning and conducting structured qual/quant research to surface user needs, behaviours, and pain points."
   },
   {
    "id": "PR-08",
    "service": "Usability Testing & Evaluation",
    "name": "Usability Test Report",
    "desc": "Conducting moderated/unmoderated usability sessions to evaluate how easily users complete key tasks."
   },
   {
    "id": "PR-09",
    "service": "Market Sizing & Opportunity Assessment",
    "name": "Market Opportunity Assessment",
    "desc": "Quantifying TAM/SAM/SOM for a product concept or expansion to validate commercial potential."
   },
   {
    "id": "PR-10",
    "service": "UX Design & Wireframing",
    "name": "UX Wireframes",
    "desc": "Translating user needs into low-to-mid fidelity interaction flows and screen layouts defining experience structure."
   },
   {
    "id": "PR-11",
    "service": "Functional Prototype Development",
    "name": "Functional Prototype",
    "desc": "Building an interactive, testable representation of a concept to validate assumptions before full build."
   },
   {
    "id": "PR-13",
    "service": "User Journey Mapping",
    "name": "User Journey Map",
    "desc": "Visualising the end-to-end experience across touchpoints to identify friction, delight, and opportunity."
   },
   {
    "id": "PR-15",
    "service": "Product Requirements Documentation",
    "name": "Product Requirements Document (PRD)",
    "desc": "Translating product intent and user needs into structured requirements engineering, design, and QA execute against."
   },
   {
    "id": "PR-16",
    "service": "Product Metrics Framework Design",
    "name": "Product Metrics Framework",
    "desc": "Defining the measurement architecture — north star, input, guardrail metrics — and how they link to outcomes."
   },
   {
    "id": "PR-17",
    "service": "Prioritisation Framework Design",
    "name": "Prioritisation Framework",
    "desc": "Building a structured, repeatable approach for evaluating and ranking initiatives against value, effort, and risk."
   },
   {
    "id": "PR-18",
    "service": "Product Operating Model Design",
    "name": "Product Operating Model",
    "desc": "Designing the rituals, tooling, decision processes, and team structures that let a product function scale."
   },
   {
    "id": "PR-19",
    "service": "Product Audit & Health Assessment",
    "name": "Product Audit Report",
    "desc": "A structured evaluation of an existing product's experience quality, debt, adoption gaps, and strategic alignment."
   },
   {
    "id": "PR-20",
    "service": "Growth Model Design",
    "name": "Growth Model",
    "desc": "Modelling how a product acquires, activates, retains, and monetises users, and the highest-leverage growth levers."
   },
   {
    "id": "PR-21",
    "service": "Experimentation Programme Design",
    "name": "Experimentation Programme Framework",
    "desc": "Building the infrastructure, methodology, and governance for structured A/B and multivariate experiments."
   },
   {
    "id": "PR-23",
    "service": "Monetisation Strategy Design",
    "name": "Monetisation Strategy Document",
    "desc": "Defining how a product generates revenue — pricing model, packaging, value metric, willingness-to-pay."
   }
  ]
 },
 "Technology & Engineering": {
  "about": "Builds, maintains, and scales the technical systems a business runs on. The function that turns requirements into working software, infrastructure, and data pipelines — keeping them reliable, secure, and evolvable over time.",
  "indices": [
   [
    "System Reliability",
    "stability, uptime & fault tolerance"
   ],
   [
    "Engineering Velocity",
    "speed & predictability of delivery"
   ],
   [
    "Technical Debt Ratio",
    "long-term maintainability of the codebase"
   ],
   [
    "Scalability Headroom",
    "capacity to grow without re-architecture"
   ],
   [
    "Security Posture",
    "resilience against threat and compliance risk"
   ]
  ],
  "capabilities": [
   "Software Architecture",
   "Frontend Development",
   "Backend Development",
   "Data Engineering",
   "Cloud & Infrastructure",
   "DevOps & CI/CD",
   "Security Engineering",
   "Quality Assurance",
   "Platform Engineering",
   "Embedded & Systems Engineering"
  ],
  "deliverables": [
   {
    "id": "TE-01",
    "service": "Custom Web Application Development",
    "name": "Deployed Web Application",
    "desc": "Designing and building a bespoke web application end-to-end to fulfil a specific business requirement."
   },
   {
    "id": "TE-02",
    "service": "API & Backend Service Development",
    "name": "Production API / Backend Service",
    "desc": "Designing and building a backend service or API exposing business logic and data to other applications."
   },
   {
    "id": "TE-03",
    "service": "Mobile Application Development",
    "name": "Published Mobile Application",
    "desc": "Building a native or cross-platform mobile application from requirements to app-store-ready release."
   },
   {
    "id": "TE-04",
    "service": "Legacy System Modernisation",
    "name": "Modernised System / Migration Report",
    "desc": "Migrating or refactoring an outdated system to a modern, maintainable equivalent without breaking functionality."
   },
   {
    "id": "TE-05",
    "service": "Codebase & Technical Debt Audit",
    "name": "Technical Audit Report",
    "desc": "A structured review of an existing codebase's health, with prioritised remediation guidance."
   },
   {
    "id": "TE-06",
    "service": "System Architecture Design",
    "name": "System Architecture Document",
    "desc": "Designing the technical architecture for a new or evolving system before a major build begins."
   },
   {
    "id": "TE-09",
    "service": "Infrastructure as Code (IaC) Implementation",
    "name": "IaC Codebase",
    "desc": "Converting manually-managed infrastructure into version-controlled, repeatable IaC definitions."
   },
   {
    "id": "TE-10",
    "service": "Security Vulnerability Assessment & Penetration Testing",
    "name": "Security Assessment Report",
    "desc": "Systematically testing an application or infrastructure for security vulnerabilities and documenting weaknesses."
   },
   {
    "id": "TE-13",
    "service": "Test Automation Framework Build",
    "name": "Automated Test Suite",
    "desc": "Designing and implementing an automated testing framework for a codebase lacking adequate coverage."
   },
   {
    "id": "TE-14",
    "service": "Performance Optimisation & Load Testing",
    "name": "Performance Optimisation Report",
    "desc": "Diagnosing and resolving performance bottlenecks through profiling, load testing, and targeted optimisation."
   },
   {
    "id": "TE-15",
    "service": "Third-Party System Integration",
    "name": "Integrated System Connection",
    "desc": "Integrating an external system, API, or service into an existing application with auth, data mapping, error handling."
   },
   {
    "id": "TE-16",
    "service": "Database Design & Migration",
    "name": "Migrated / Implemented Database",
    "desc": "Designing a new database schema or migrating data between systems, ensuring integrity and minimal downtime."
   },
   {
    "id": "TE-17",
    "service": "Data Pipeline & ETL Development",
    "name": "Data Pipeline",
    "desc": "Building automated pipelines that extract, transform, and load data from source systems into a usable data store."
   },
   {
    "id": "TE-21",
    "service": "Platform / Internal Developer Tooling Build",
    "name": "Internal Developer Platform / Tool",
    "desc": "Building internal tools or platforms that improve the productivity of other engineers."
   }
  ]
 }
};
